### ISSUE TITLE
Crop Coefficient module indexing errors

### ISSUE THREAD

**Issue by dking444w** [cgmorton/et-demands#9]
crop_coefficients module has two indexing error.  Bug is in both both develop and master.

# crop_coefficents indexing errors

def read_crop_coefs(fn):

# line:

    curve_type = a[2, 2:]

# should be:

    curve_type = a[3, 2:]
    
# lines:

        if curve_type[i] == '3':
            percents = a[6:36, 0]
        else:
            percents = a[6:41, 1]
# should be:

        if curve_type[i] == '3':
            percents = a[6:37, 0]
        else:
            percents = a[6:41, 1]

**Comment by cgmorton** [comment]
Dave, thanks for finding this!  Do I also have something backwards in the CropCoefs.txt file then?  Are the type labels in row 5 (index 4) swapped, so column 0 should be for type 3 (since there are 31 values) and column 1 should be for types 1-2-4 (since there are 35 values).

**Comment by cgmorton** [comment]
The second part of the original issue addressing the percents column was not actually an issue because the percent values are never used in the code anywhere.
